apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: videos-web-rollout
  namespace: default
spec:
  service: videos-web
  backends:
  - service: videos-web
    weight: "70"
  - service: videos-web-canary
    weight: "30"